# Настройки чатов
chats:
  local:
    enable: true # Включение локального чата
    range: 100 # Радиус локального чата
    cooldown: -1 # Задержка локального чата (-1 для отключения)
    viewing-perms: 'javachats.local.view' # Право на чтение
    sending-perms: 'javachats.local.send' # Право на отправку
    sound: '' # Звук при отправке
  global:
    enable: true # Включение глобального чата
    range: -1 # Радиус (-1 для бесконечного)
    symbol: '!' # Символ глобального чата в начале сообщения
    cooldown: -1 # Задержка глобального чата (-1 для отключения)
    viewing-perms: 'javachats.global.view' # Право на чтение
    sending-perms: 'javachats.global.send' # Право на отправку
    sound: '' # Звук при отправке

# Настройки пинга в чате
ping-chat:
  enabled: true # Включить пинг игроков
  title:
    fade-in: 10 # Время появления титра в тиках
    stay: 70 # Время отображения титра
    fade-out: 20 # Время исчезновения титра
  sound:
    enable: true # Включить звук пинга
    name: 'BLOCK_NOTE_BLOCK_GUITAR' # Название звука
    volume: 0.7 # Громкость
    pitch: 2.0 # Тональность
    category: 'MASTER' # Категория звука

# Оповещения о входе/выходе
join-quit:
  join:
    enable: true # Оповещение о входе
  quit:
    enable: true # Оповещение о выходе

# Настройки анти-капса
settings:
  anti-caps-percent: 75 # Процент капса в сообщении
  anti-caps-min-length: 4 # Минимальная длина сообщения для проверки

# Интеграция с Discord
discord:
  tech-role: '1391468653052035251' # ID технической роли Discord
  debug: true # Отладка интеграции с Discord
