name: JavaChats
version: 1.0
main: ru.javaroot.javachats.JavaChat
api-version: '1.21'
authors: [JavaRoot]

commands:
  javachats:
    permission: javachats.admin
    usage: /javachats reload
  msg:
    aliases: [tell, w]
    permission: javachats.msg
    usage: /msg <игрок> <сообщение>
  aihelper:
    permission: javachats.admin
    usage: /aihelper add <plus|minus> <сообщение>

permissions:
  javachats.admin:
    default: op
  javachats.local.view:
    default: true
  javachats.local.send:
    default: true
  javachats.global.view:
    default: true
  javachats.global.send:
    default: true
  javachats.msg:
    default: true
